#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_


#include "stdint.h"

#if defined(BOARD_KIK0001)
#define APP_CONFIG_RX_PIN_NUMBER  6
#define APP_CONFIG_TX_PIN_NUMBER  26
#elif defined(BOARD_PCA10056)
#define APP_CONFIG_RX_PIN_NUMBER  8
#define APP_CONFIG_TX_PIN_NUMBER  6
#endif

#define NRF_LOG_BACKEND_UART_RX_PIN APP_CONFIG_RX_PIN_NUMBER
#define NRF_LOG_BACKEND_UART_TX_PIN APP_CONFIG_TX_PIN_NUMBER

#define HCI_UART_RX_PIN APP_CONFIG_RX_PIN_NUMBER
#define HCI_UART_TX_PIN APP_CONFIG_TX_PIN_NUMBER

#define APP_RX_PIN_NUMBER APP_CONFIG_RX_PIN_NUMBER
#define APP_TX_PIN_NUMBER APP_CONFIG_TX_PIN_NUMBER

// Baudrate
#define APP_CONFIG_DEFAULT_UART_BAUDRATE UARTE_BAUDRATE_BAUDRATE_Baud1M
// #define APP_CONFIG_DEFAULT_UART_BAUDRATE UARTE_BAUDRATE_BAUDRATE_Baud115200

#define NRFX_UARTE_DEFAULT_CONFIG_BAUDRATE APP_CONFIG_DEFAULT_UART_BAUDRATE
#define NRFX_UART_DEFAULT_CONFIG_BAUDRATE APP_CONFIG_DEFAULT_UART_BAUDRATE
#define UART_DEFAULT_CONFIG_BAUDRATE APP_CONFIG_DEFAULT_UART_BAUDRATE
#define NRF_LOG_BACKEND_UART_BAUDRATE APP_CONFIG_DEFAULT_UART_BAUDRATE
#define HCI_UART_BAUDRATE APP_CONFIG_DEFAULT_UART_BAUDRATE

// Log
#define NRF_LOG_DEFAULT_LEVEL NRF_LOG_SEVERITY_DEBUG

// FIFO
#define APP_FIFO_ENABLED 1

// CLI
#define NRF_CLI_ENABLED 1

// UART1
#define UART1_ENABLED 1
#define NRFX_UARTE_ENABLED 1
#define NRFX_UARTE0_ENABLED 1
#define NRFX_UARTE0_USE_EASY_DMA 1
#define NRFX_UARTE1_ENABLED 1

// TWI
#define TWI_ENABLED 1
#define TWI0_ENABLED 1
#define TWI0_USE_EASY_DMA 1
#define NRFX_TWI_ENABLED 1
#define NRFX_TWIM_ENABLED 1
#define NRFX_TWI0_ENABLED 1
#define NRFX_TWIM0_ENABLED 1

// SPI
#define NRF_SPI_MNGR_ENABLED 1
#define NRFX_SPIM_ENABLED 1
#define NRFX_SPIM0_ENABLED 1
#define SPI_ENABLED 1
#define SPI0_ENABLED 1
#define SPI0_USE_EASY_DMA 1
#define NRFX_SPI_ENABLED 1
#define NRFX_SPI0_ENABLED 1

// Disable NFC
#define NFC_ENABLED 0
#define CONFIG_NFCT_PINS_AS_GPIOS

#endif /* APP_CONFIG_H_ */
